backend:
  name: git-gateway
  branch: the-canney-valley

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", default: "", format: "MMMM Do YYYY"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          default: "miscellaneous", 
          field: {
            label: "Tag",
            name: "tag_name",
            widget: "string"
          }
      }
      - {
          label: "Categories", 
          name: "categories", 
          widget: "list", 
          default: "general", 
          field: {
            label: Category",
            name: "category_name",
            widget: "string"
          }
      }

# Adding featured images
# https://www.netlifycms.org/docs/widgets/image/#image